name: PotatoMan
main: com.benjisoft.Potato.PotatoTest
version: 1.3
commands:
   potato:
      description: Get dem potatos
      usage: /potato
   potato info:
      description: Find out more about me!
      usage: /potato info
   carrot:
      description: Don't touch it!
      usage: /carrot