name: PotatoMan
main: com.benjisoft.Potato.PotatoTest
version: 1.2
commands:
   potato:
      description: Get dem potatos
      usage: /potato
   carrot:
      description: Don't touch it!
      usage: /carrot